// ============================================================
// RoboKid Platform — TypeScript Type Definitions
// Kenya CBC Competency-Based Curriculum (Grade 1-3)
// ============================================================

/** Supported grade levels in Lower Primary */
export type Grade = 1 | 2 | 3;

/** The 7 rationalized CBC learning areas (2025 KICD framework) */
export type Subject =
  | 'mathematics'
  | 'environmental'
  | 'english'
  | 'kiswahili'
  | 'indigenous'
  | 'creative'
  | 'religious';

/** Supported languages for translation */
export type Language = 'english' | 'kiswahili' | 'kikuyu' | 'luo' | 'somali';

/** Language display metadata */
export interface LanguageInfo {
  code: Language;
  label: string;
  nativeLabel: string;
  flag: string; // emoji
}

/** A single curriculum topic */
export interface Topic {
  id: string;
  title: string;
  description: string;
  grade: Grade;
  subject: Subject;
  term: 1 | 2 | 3;
  strand: string;
  subStrand: string;
  learningOutcomes: string[];
  suggestedActivities: string[];
  keywords: string[];
}

/** A curriculum subject with metadata */
export interface SubjectInfo {
  id: Subject;
  name: string;
  icon: string;
  color: string;
  gradient: string;
  description: string;
  topics: Topic[];
}

/** Exam question types */
export type QuestionType =
  | 'multiple_choice'
  | 'fill_blank'
  | 'true_false'
  | 'matching'
  | 'picture_based'
  | 'short_answer';

/** A single exam question */
export interface ExamQuestion {
  id: string;
  grade: Grade;
  subject: Subject;
  type: QuestionType;
  question: string;
  options?: string[];
  correctAnswer: string;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  term: 1 | 2 | 3;
  strand: string;
  imagePrompt?: string; // for Gemini image generation
  kenyanContext?: string; // cultural context note
}

/** An exam session */
export interface ExamSession {
  id: string;
  grade: Grade;
  subject: Subject;
  questions: ExamQuestion[];
  answers: Record<string, string>;
  score: number;
  totalQuestions: number;
  startedAt: Date;
  completedAt?: Date;
}

/** Game types available */
export type GameType =
  | 'memory_match'
  | 'word_search'
  | 'math_race'
  | 'picture_quiz'
  | 'puzzle'
  | 'drag_drop';

/** A game configuration */
export interface GameConfig {
  id: string;
  type: GameType;
  title: string;
  description: string;
  grade: Grade;
  subject: Subject;
  difficulty: 'easy' | 'medium' | 'hard';
  timeLimit?: number; // seconds
  data: Record<string, unknown>;
}

/** Puzzle generated by Gemini */
export interface GeneratedPuzzle {
  id: string;
  grade: Grade;
  subject: Subject;
  language: Language;
  question: string;
  options?: string[];
  answer: string;
  hint?: string;
  explanation?: string;
  kenyanContext: string;
  generatedAt: Date;
}

/** API request for Gemini content generation */
export interface GeminiContentRequest {
  grade: Grade;
  subject: Subject;
  language: Language;
  contentType: 'puzzle' | 'story' | 'quiz' | 'lesson' | 'vocabulary';
  topic?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

/** API response from Gemini content generation */
export interface GeminiContentResponse {
  content: string;
  language: Language;
  metadata: {
    grade: Grade;
    subject: Subject;
    contentType: string;
    generatedAt: string;
  };
}

/** API request for translation */
export interface TranslateRequest {
  text: string;
  targetLanguage: Language;
  grade: Grade;
  context?: string;
}

/** API response for translation */
export interface TranslateResponse {
  originalText: string;
  translatedText: string;
  targetLanguage: Language;
}

/** User subscription tier */
export type SubscriptionTier = 'free' | 'premium';

/** User progress tracking */
export interface UserProgress {
  grade: Grade;
  subjectProgress: Record<Subject, {
    topicsCompleted: number;
    totalTopics: number;
    quizzesTaken: number;
    averageScore: number;
    lastActivity: Date;
  }>;
  gamesPlayed: number;
  totalScore: number;
  streak: number; // consecutive days
  achievements: string[];
}

/** Playbook section for documentation */
export interface PlaybookSection {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  color: string;
  content: string;
}

/** Subject card display data */
export interface SubjectCardData {
  subject: Subject;
  name: string;
  icon: string;
  color: string;
  gradient: string;
  description: string;
  topicCount: number;
  progress: number; // 0-100
}
